create_event:
  name: Create event
  description: Add a new calendar event.
  target:
    entity:
      integration: local_calendar
      domain: calendar
  fields:
    summary:
      name: Summary
      description: Acts as the title of the event.
      required: true
      example: "Bowling"
      selector:
        text:
    description:
      name: Description
      description: The description of the event. Optional.
      example: "Birthday bowling"
      selector:
        text:
    dtstart:
      name: Start time
      description: The date or date and time the event should start.
      example: "2022-03-22"
      selector:
        text:
    dtend:
      name: End time
      description: The date or date and time the event should end.
      example: "2022-03-22 22:00:00"
      selector:
        text:
    rrule:
      name: Recurrence rule
      description: The rule that describes the occurrences of the event.
      example: "FREQ=WEEKLY"
      selector:
        text:
delete_event:
  name: Delete Event
  description: Delete a calendar event.
  target:
    entity:
      integration: local_calendar
      domain: calendar
  fields:
    uid:
      name: Unique Identifier
      description: The unique identifier if the calendar event and all of its recurring events
      required: true
      selector:
        text:
    recurrence_id:
      name: Recurrence identifier
      description: The unique identifier of a specific event in a recurring event series.
      required: false
      selector:
        text:
    recurrence_range:
      name: Recurrence Range
      description: When specified as "THISANDFUTURE" deletes all instances of the recurring event at and beyond the specified recurrence_id.
      required: false
      selector:
        text:
